Repository insightsengineering/formatters, pull requests merged in 2023-07, with the labels that each got.

#174 Update `export_as_txt` to print split label when using `page_by` with one level
  R/pagination.R
Labels: sme

#176 Create `obj_align`, `fmt_config` constructor/class
  NAMESPACE
  NEWS.md
  R/format_value.R
  R/generics.R
  _pkgdown.yml
  man/fmt_config.Rd
  man/lab_name.Rd
  tests/testthat/test-formatters.R
Labels: sme

#179 align standard is NULL to be set in rlistings
  R/format_value.R
  R/generics.R
  man/fmt_config.Rd
  man/lab_name.Rd
  tests/testthat/test-formatters.R
Labels: enhancement, sme

#181 Revert defaults to avoid `NULL` assigns before `rlistings`' PR
  NEWS.md
  R/format_value.R
  man/fmt_config.Rd
  tests/testthat/test-formatters.R
Labels: bug, sme

#177 updating description, news, change version to 0.5.1, [skip vbump]
  DESCRIPTION
  NEWS.md
Labels: sme

#183 447 remove formatters from teal packages
  staged_dependencies.yaml
Labels: core
