Repository insightsengineering/formatters, pull requests merged in 2023-10, with the labels that each got.

#204 [skip vbump] Internal release candidate 0.5.3
  DESCRIPTION
  NEWS.md
  R/generics.R
  man/figures/formatters_hexSticker.pdf
  man/figures/formatters_hexSticker.png
  man/make_row_df.Rd
  tests/testthat/test-formatters.R
Labels: sme

#206 205 paginate mpfs listing@main
  NEWS.md
  R/pagination.R
Labels: sme

#214 Support for newlines
  NEWS.md
  R/matrix_form.R
  R/tostring.R
  tests/testthat/test-pagination.R
Labels: enhancement, sme

#210 Improve pagination error print (re-do with verbose + details)
  NEWS.md
  R/pagination.R
Labels: documentation, enhancement, sme

#215 Add newline character support for ref footnotes
  R/matrix_form.R
  R/pagination.R
  R/tostring.R
  man/wrap_string.Rd
  tests/testthat/test-exporters.R
  tests/testthat/test-txt_wrap.R
  vignettes/formatters.Rmd
Labels: bug, sme

#216 [skip vbump] Release candidate v0.5.4
  DESCRIPTION
  NEWS.md
Labels: sme, release

#219 Apply styler, fix lint
  .lintr
  NEWS.md
  R/format_value.R
  R/generics.R
  R/labels.R
  R/matrix_form.R
  R/mpf_exporters.R
  R/page_size.R
  R/pagination.R
  R/tostring.R
  man/decimal_align.Rd
  man/matrix_form.Rd
  man/paginate_indices.Rd
  man/wrap_string.Rd
  tests/testthat/setup.R
  tests/testthat/test-exporters.R
  tests/testthat/test-formatters.R
  tests/testthat/test-pagination.R
  tests/testthat/test-txt_wrap.R
  vignettes/formatters.Rmd
Labels: sme
