Repository insightsengineering/formatters, pull requests merged in 2023-11, with the labels that each got.

#225 Support for combining duplicate ref footnotes
  R/matrix_form.R
  R/tostring.R
  tests/testthat/test-exporters.R
  tests/testthat/test-formatters.R
Labels: sme

#224 Fix separator div in case of wrapping
  NEWS.md
  R/generics.R
  R/matrix_form.R
  R/tostring.R
  man/MatrixPrintForm.Rd
  tests/testthat/test-txt_wrap.R
Labels: bug, sme

#231 Fixing infinite loop for specific strings (e.g. "10 . 4", width of 2)
  NEWS.md
  R/tostring.R
  tests/testthat/test-txt_wrap.R
Labels: bug, sme, priority
