Repository insightsengineering/formatters, pull requests merged in 2024-02, with the labels that each got.

#256 Fix pkgdown redirect
  DESCRIPTION
  man/formatters-package.Rd
Labels: bug, core

#260 Fix oneliner error and addition of `basic_listing_mf` for testing
  NAMESPACE
  R/matrix_form.R
  R/pagination.R
  man/basic_matrix_form.Rd
  man/test_matrix_form.Rd
  tests/testthat/Rplots.pdf
  tests/testthat/test-exporters.R
  tests/testthat/test-listings.R
Labels: bug, enhancement, sme, tests

#253 strict options in tests; few minor enhancements
  .pre-commit-config.yaml
  DESCRIPTION
  R/format_value.R
  R/page_size.R
  R/pagination.R
  R/tostring.R
  man/basic_pagdf.Rd
  man/font_lcpi.Rd
  man/format_value.Rd
  man/padstr.Rd
  man/paginate_indices.Rd
  man/round_fmt.Rd
  man/spans_to_viscell.Rd
  man/sprintf_format.Rd
  tests/testthat/setup-options.R
  tests/testthat/test-txt_wrap.R
Labels: sme
