Repository insightsengineering/formatters, pull requests merged in 2024-01, with the labels that each got.

#245 snapshot fix for new format
  tests/testthat/test-formatters.R
Labels: automation, sme

#226 allow content row in the end
  NEWS.md
  R/matrix_form.R
  R/pagination.R
  tests/testthat/test-pagination.R
Labels: sme, poc

#250 Fix bug in `format_value` causing warning for NAs
  DESCRIPTION
  NEWS.md
  R/format_value.R
  man/nlines.Rd
  tests/testthat/test-formatters.R
Labels: sme

#254 fix deps of roxygenize pre-commit hook
  .pre-commit-config.yaml
  DESCRIPTION
Labels: sme
