Repository insightsengineering/formatters, pull requests merged in 2024-05, with the labels that each got.

#284 Bumps `{rmarkdown}` minimal version
  DESCRIPTION
Labels: core

#290 Hot fix for page number bug
  R/pagination.R
  tests/testthat/test-exporters.R
Labels: sme, priority

#292 Fix pagination LBT01 issue count
  R/pagination.R
Labels: bug, sme

#294 [skip vbump] preping for release tag 0.5.7
  DESCRIPTION
  NEWS.md
Labels: sme
