Repository insightsengineering/formatters, pull requests merged in 2024-04, with the labels that each got.

#273 Hot-fix for list pagination for {rtables} tests
  R/mpf_exporters.R
Labels: sme, priority

#276 Adding more details to test mock examples
  NEWS.md
  R/matrix_form.R
  R/pagination.R
  man/basic_pagdf.Rd
  man/test_matrix_form.Rd
  tests/testthat/setup.R
  tests/testthat/test-exporters.R
  tests/testthat/test-formatters.R
  tests/testthat/test-matrix_form.R
  tests/testthat/test-print.R
  tests/testthat/test-ref_fnotes.R
  tests/testthat/test-txt_wrap.R
Labels: enhancement, sme, tests

#275 update version number to 0.5.6, preping for cran release [skip vbump]
  DESCRIPTION
  NEWS.md
Labels: sme

#277 Trial fix req validation
  R/generics.R
  man/make_row_df.Rd
Labels: automation, sme
