Repository insightsengineering/formatters, pull requests merged in 2024-03, with the labels that each got.

#227 add page number
  DESCRIPTION
  NAMESPACE
  R/mpf_exporters.R
  R/pagination.R
  R/tostring.R
  R/zzz.R
  _pkgdown.yml
  man/default_horizontal_sep.Rd
  man/default_page_number.Rd
  man/export_as_pdf.Rd
  man/export_as_rtf.Rd
  man/export_as_txt.Rd
  man/paginate_indices.Rd
  tests/testthat/test-exporters.R
  tests/testthat/test-formatters.R
  tests/testthat/test-pagination.R
Labels: sme, poc

#263 Fix var labels when named
  NEWS.md
  R/labels.R
  tests/testthat/test-formatters.R
Labels: bug, sme

#267 Verdepcheck fixes
  DESCRIPTION
Labels: sme

#268 Add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: documentation, sme
